app = "prod-activity-viewers"
primary_region = "iad"

[[vm]]
  size = "shared-cpu-8x"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [services.concurrency]
      type = "connections"
      hard_limit = 4000
      soft_limit = 3000
  
  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    port = 8080
    interval = 10000
    timeout = 2000
